import 'dart:ui';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _langCode = 'de';
  static const String _key = 'language_code';

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'de', 'name': 'Deutsch', 'flag': '🇩🇪'},
    {'code': 'en', 'name': 'English', 'flag': '🇬🇧'},
    {'code': 'tr', 'name': 'Türkçe', 'flag': '🇹🇷'},
    {'code': 'fr', 'name': 'Français', 'flag': '🇫🇷'},
    {'code': 'es', 'name': 'Español', 'flag': '🇪🇸'},
  ];

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString(_key);
    if (saved != null) {
      _langCode = saved;
    } else {
      // Systemsprache automatisch erkennen – alle Locales prüfen (Fallback-Kette)
      const supported = ['de', 'en', 'tr', 'fr', 'es'];
      final systemLocales = PlatformDispatcher.instance.locales;
      String detected = 'en';
      for (final locale in systemLocales) {
        final code = locale.languageCode;
        if (supported.contains(code)) {
          detected = code;
          break;
        }
      }
      _langCode = detected;
    }
  }

  Future<void> setLanguage(String code) async {
    _langCode = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
  }

  String get currentCode => _langCode;

  String t(String key) {
    return _translations[_langCode]?[key] ??
        _translations['de']?[key] ??
        key;
  }

  String translateCoin(String serverName) {
    return _coinTranslations[serverName]?[_langCode] ?? serverName;
  }

  String getCurrencyName(String code) {
    return _currencyNames[code]?[_langCode] ??
        _currencyNames[code]?['en'] ??
        code;
  }

  /// Formatiert einen Geldbetrag locale-gerecht:
  /// DE/TR/ES/FR → 10.000,50  |  EN → 10,000.50
  String formatAmount(double value, {int decimals = 2}) {
    final pattern = '#,##0.${'0' * decimals}';
    return NumberFormat(pattern, _langCode).format(value);
  }

  // Länderkeywords für die Suche (sprachunabhängig, alle Aliases)
  static const Map<String, List<String>> currencyCountryKeywords = {
    'EUR': ['europe', 'europa', 'avrupa', 'eu', 'eurozone', 'germany', 'deutschland', 'allemagne', 'alemania', 'france', 'frankreich', 'francia', 'italy', 'italien', 'italie', 'italia', 'spain', 'spanien', 'espagne', 'españa'],
    'USD': ['usa', 'united states', 'vereinigte staaten', 'états-unis', 'estados unidos', 'america', 'amérique', 'américa'],
    'TRY': ['turkey', 'türkei', 'turquie', 'turquía', 'türkiye'],
    'GBP': ['uk', 'britain', 'england', 'großbritannien', 'royaume-uni', 'reino unido', 'united kingdom'],
    'CHF': ['switzerland', 'schweiz', 'suisse', 'suiza'],
    'JPY': ['japan', 'japon', 'japón'],
    'CNY': ['china', 'chine', 'volksrepublik'],
    'RUB': ['russia', 'russland', 'russie', 'rusia'],
    'INR': ['india', 'indien', 'inde'],
    'BRL': ['brazil', 'brasilien', 'brésil', 'brasil'],
    'ZAR': ['south africa', 'südafrika', 'afrique du sud', 'sudáfrica'],
    'AUD': ['australia', 'australien', 'australie'],
    'CAD': ['canada', 'kanada'],
    'NZD': ['new zealand', 'neuseeland', 'nouvelle-zélande', 'nueva zelanda'],
    'SGD': ['singapore', 'singapur'],
    'HKD': ['hong kong', 'hongkong'],
    'KRW': ['korea', 'südkorea', 'corée', 'corea'],
    'MXN': ['mexico', 'mexiko', 'mexique', 'méxico'],
    'SEK': ['sweden', 'schweden', 'suède', 'suecia'],
    'NOK': ['norway', 'norwegen', 'norvège', 'noruega'],
    'DKK': ['denmark', 'dänemark', 'danemark', 'dinamarca'],
    'PLN': ['poland', 'polen', 'pologne', 'polonia'],
    'CZK': ['czech', 'tschechien', 'tchéquie', 'chequia', 'tschechische'],
    'HUF': ['hungary', 'ungarn', 'hongrie', 'hungría'],
    'RON': ['romania', 'rumänien', 'roumanie', 'rumanía'],
    'BGN': ['bulgaria', 'bulgarien', 'bulgarie'],
    'HRK': ['croatia', 'kroatien', 'croatie', 'croacia'],
    'ISK': ['iceland', 'island', 'islande', 'islandia'],
    'THB': ['thailand', 'thaïlande', 'tailandia'],
    'MYR': ['malaysia', 'malaysien', 'malaisie', 'malasia'],
    'IDR': ['indonesia', 'indonesien', 'indonésie'],
    'PHP': ['philippines', 'philippinen', 'filipinas'],
    'ILS': ['israel', 'israël'],
    'AED': ['emirates', 'emirate', 'émirats', 'emiratos', 'uae', 'vae', 'dubai', 'abu dhabi'],
    'SAR': ['saudi', 'arabia', 'arabien', 'arabie', 'riyadh'],
    'EGP': ['egypt', 'ägypten', 'égypte', 'egipto', 'cairo'],
    'ARS': ['argentina', 'argentinien'],
    'CLP': ['chile', 'chili'],
    'COP': ['colombia', 'kolumbien', 'colombie'],
    'PEN': ['peru', 'perú'],
  };

  static const Map<String, Map<String, String>> _currencyNames = {
    'EUR': {'de': 'Euro',              'en': 'Euro',              'tr': 'Euro',              'fr': 'Euro',              'es': 'Euro'},
    'USD': {'de': 'US-Dollar',         'en': 'US Dollar',         'tr': 'ABD Doları',        'fr': 'Dollar américain',  'es': 'Dólar estadounidense'},
    'GBP': {'de': 'Britisches Pfund',  'en': 'British Pound',     'tr': 'İngiliz Sterlini',  'fr': 'Livre sterling',    'es': 'Libra esterlina'},
    'CHF': {'de': 'Schweizer Franken', 'en': 'Swiss Franc',       'tr': 'İsviçre Frangı',    'fr': 'Franc suisse',      'es': 'Franco suizo'},
    'JPY': {'de': 'Japanischer Yen',   'en': 'Japanese Yen',      'tr': 'Japon Yeni',        'fr': 'Yen japonais',      'es': 'Yen japonés'},
    'CNY': {'de': 'Chinesischer Yuan', 'en': 'Chinese Yuan',      'tr': 'Çin Yuanı',         'fr': 'Yuan chinois',      'es': 'Yuan chino'},
    'TRY': {'de': 'Türkische Lira',    'en': 'Turkish Lira',      'tr': 'Türk Lirası',       'fr': 'Livre turque',      'es': 'Lira turca'},
    'RUB': {'de': 'Russischer Rubel',  'en': 'Russian Ruble',     'tr': 'Rus Rublesi',       'fr': 'Rouble russe',      'es': 'Rublo ruso'},
    'INR': {'de': 'Indische Rupie',    'en': 'Indian Rupee',      'tr': 'Hint Rupisi',       'fr': 'Roupie indienne',   'es': 'Rupia india'},
    'BRL': {'de': 'Brasilianischer Real', 'en': 'Brazilian Real', 'tr': 'Brezilya Reali',    'fr': 'Réal brésilien',   'es': 'Real brasileño'},
    'ZAR': {'de': 'Südafrikanischer Rand', 'en': 'South African Rand', 'tr': 'Güney Afrika Randı', 'fr': 'Rand sud-africain', 'es': 'Rand sudafricano'},
    'AUD': {'de': 'Australischer Dollar', 'en': 'Australian Dollar', 'tr': 'Avustralya Doları', 'fr': 'Dollar australien', 'es': 'Dólar australiano'},
    'CAD': {'de': 'Kanadischer Dollar', 'en': 'Canadian Dollar',  'tr': 'Kanada Doları',     'fr': 'Dollar canadien',   'es': 'Dólar canadiense'},
    'NZD': {'de': 'Neuseeland-Dollar', 'en': 'New Zealand Dollar', 'tr': 'Yeni Zelanda Doları', 'fr': 'Dollar néo-zélandais', 'es': 'Dólar neozelandés'},
    'SGD': {'de': 'Singapur-Dollar',   'en': 'Singapore Dollar',  'tr': 'Singapur Doları',   'fr': 'Dollar de Singapour', 'es': 'Dólar de Singapur'},
    'HKD': {'de': 'Hongkong-Dollar',   'en': 'Hong Kong Dollar',  'tr': 'Hong Kong Doları',  'fr': 'Dollar de Hong Kong', 'es': 'Dólar de Hong Kong'},
    'KRW': {'de': 'Südkoreanischer Won', 'en': 'South Korean Won', 'tr': 'Güney Kore Wonu',  'fr': 'Won sud-coréen',    'es': 'Won surcoreano'},
    'MXN': {'de': 'Mexikanischer Peso', 'en': 'Mexican Peso',     'tr': 'Meksika Pesosu',    'fr': 'Peso mexicain',     'es': 'Peso mexicano'},
    'SEK': {'de': 'Schwedische Krone', 'en': 'Swedish Krona',     'tr': 'İsveç Kronası',     'fr': 'Couronne suédoise', 'es': 'Corona sueca'},
    'NOK': {'de': 'Norwegische Krone', 'en': 'Norwegian Krone',   'tr': 'Norveç Kronası',    'fr': 'Couronne norvégienne', 'es': 'Corona noruega'},
    'DKK': {'de': 'Dänische Krone',    'en': 'Danish Krone',      'tr': 'Danimarka Kronası', 'fr': 'Couronne danoise',  'es': 'Corona danesa'},
    'PLN': {'de': 'Polnischer Złoty',  'en': 'Polish Złoty',      'tr': 'Polonya Zlotisi',   'fr': 'Złoty polonais',    'es': 'Esloti polaco'},
    'CZK': {'de': 'Tschechische Krone', 'en': 'Czech Koruna',     'tr': 'Çek Korunası',      'fr': 'Couronne tchèque',  'es': 'Corona checa'},
    'HUF': {'de': 'Ungarischer Forint', 'en': 'Hungarian Forint', 'tr': 'Macar Forinti',     'fr': 'Forint hongrois',   'es': 'Forinto húngaro'},
    'RON': {'de': 'Rumänischer Leu',   'en': 'Romanian Leu',      'tr': 'Rumen Leyi',        'fr': 'Leu roumain',       'es': 'Leu rumano'},
    'BGN': {'de': 'Bulgarischer Lew',  'en': 'Bulgarian Lev',     'tr': 'Bulgar Levası',     'fr': 'Lev bulgare',       'es': 'Lev búlgaro'},
    'HRK': {'de': 'Kroatische Kuna',   'en': 'Croatian Kuna',     'tr': 'Hırvatistan Kunası','fr': 'Kuna croate',       'es': 'Kuna croata'},
    'ISK': {'de': 'Isländische Kröne', 'en': 'Icelandic Króna',   'tr': 'İzlanda Kronası',   'fr': 'Couronne islandaise', 'es': 'Corona islandesa'},
    'THB': {'de': 'Thailändischer Baht', 'en': 'Thai Baht',       'tr': 'Tayland Bahtı',     'fr': 'Baht thaïlandais',  'es': 'Baht tailandés'},
    'MYR': {'de': 'Malaysischer Ringgit', 'en': 'Malaysian Ringgit', 'tr': 'Malezya Ringgiti', 'fr': 'Ringgit malaisien', 'es': 'Ringgit malayo'},
    'IDR': {'de': 'Indonesische Rupiah', 'en': 'Indonesian Rupiah', 'tr': 'Endonezya Rupiahı', 'fr': 'Roupie indonésienne', 'es': 'Rupia indonesia'},
    'PHP': {'de': 'Philippinischer Peso', 'en': 'Philippine Peso', 'tr': 'Filipin Pesosu',   'fr': 'Peso philippin',    'es': 'Peso filipino'},
    'ILS': {'de': 'Israelischer Schekel', 'en': 'Israeli Shekel', 'tr': 'İsrail Şekeli',     'fr': 'Shekel israélien',  'es': 'Séquel israelí'},
    'AED': {'de': 'VAE-Dirham',        'en': 'UAE Dirham',        'tr': 'BAE Dirhemi',       'fr': 'Dirham des EAU',    'es': 'Dírham de EAU'},
    'SAR': {'de': 'Saudi-Riyal',       'en': 'Saudi Riyal',       'tr': 'Suudi Riyali',      'fr': 'Riyal saoudien',    'es': 'Riyal saudí'},
    'EGP': {'de': 'Ägyptisches Pfund', 'en': 'Egyptian Pound',    'tr': 'Mısır Poundu',      'fr': 'Livre égyptienne',  'es': 'Libra egipcia'},
    'ARS': {'de': 'Argentinischer Peso', 'en': 'Argentine Peso',  'tr': 'Arjantin Pesosu',   'fr': 'Peso argentin',     'es': 'Peso argentino'},
    'CLP': {'de': 'Chilenischer Peso', 'en': 'Chilean Peso',      'tr': 'Şili Pesosu',       'fr': 'Peso chilien',      'es': 'Peso chileno'},
    'COP': {'de': 'Kolumbianischer Peso', 'en': 'Colombian Peso', 'tr': 'Kolombiya Pesosu',  'fr': 'Peso colombien',    'es': 'Peso colombiano'},
    'PEN': {'de': 'Peruanischer Sol',  'en': 'Peruvian Sol',      'tr': 'Peru Solu',         'fr': 'Sol péruvien',      'es': 'Sol peruano'},
  };

  static const Map<String, Map<String, String>> _coinTranslations = {
    'Gold (1g)':  {'de': 'Gold (1g)',    'en': 'Gold (1g)',    'tr': 'Altın (1g)',  'fr': 'Or (1g)',     'es': 'Oro (1g)'},
    'Gold (1kg)': {'de': 'Gold (1kg)',   'en': 'Gold (1kg)',   'tr': 'Altın (1kg)', 'fr': 'Or (1kg)',    'es': 'Oro (1kg)'},
    'Unze (1 oz)':{'de': 'Unze (1 oz)', 'en': 'Ounce (1 oz)', 'tr': 'Ons (1 oz)',  'fr': 'Once (1 oz)', 'es': 'Onza (1 oz)'},
    'Silber (1g)':{'de': 'Silber (1g)', 'en': 'Silver (1g)',  'tr': 'Gümüş (1g)',  'fr': 'Argent (1g)', 'es': 'Plata (1g)'},
    'Silber (1kg)':{'de':'Silber (1kg)','en': 'Silver (1kg)', 'tr': 'Gümüş (1kg)', 'fr': 'Argent (1kg)','es': 'Plata (1kg)'},
    'Altın Takı': {'de': 'Gold-Schmuck', 'en': 'Gold Jewelry', 'tr': 'Altın Takı',  'fr': 'Bijou or',    'es': 'Joya de oro'},
    'Gümüş Takı': {'de': 'Silber-Schmuck','en': 'Silver Jewelry','tr': 'Gümüş Takı','fr': 'Bijou argent','es': 'Joya de plata'},
  };

  static const Map<String, Map<String, String>> _translations = {
    'de': {
      // App
      'app_title': 'KaratExchange',
      'tab_currency': 'Währung',
      'tab_gold': 'Gold',
      'tab_settings': 'Einstellungen',
      'tab_debug': 'Debug',
      // Settings
      'settings_title': 'Einstellungen',
      'settings_design': 'Design',
      'settings_light': 'Hell',
      'settings_dark': 'Dunkel',
      'settings_system': 'System-Standard',
      'settings_system_sub': 'Passt sich automatisch an dein Gerät an',
      'settings_haptic': 'Haptisches Feedback',
      'settings_haptic_all': 'Alle Aktionen',
      'settings_haptic_all_sub': 'Vibration bei allen Interaktionen',
      'settings_haptic_important': 'Nur wichtige',
      'settings_haptic_important_sub': 'Vibration nur bei wichtigen Aktionen',
      'settings_haptic_off': 'Aus',
      'settings_haptic_off_sub': 'Keine Vibration',
      'settings_language': 'Sprache',
      'settings_zakat': 'Zakat-Modus',
      'settings_zakat_sub': 'Zakat-Berechnung im Gold-Tab anzeigen',
      'settings_legal': 'Rechtliches',
      'settings_privacy': 'Datenschutzerklärung',
      'settings_info': 'Deine Einstellungen werden lokal gespeichert und nicht übertragen.',
      // Gold Tab
      'gold_coin': 'Münze',
      'gold_currency': 'Währung',
      'gold_quantity': 'Anzahl',
      'gold_add': 'Hinzufügen',
      'gold_spot': 'Spot',
      'gold_dealer': 'Händler',
      'gold_total_spot': 'Gesamt Spot',
      'gold_total_dealer': 'Gesamt Händler',
      'gold_remove_all': 'Alle entfernen',
      'gold_share': 'Warenkorb teilen',
      'gold_added_to_cart': 'zum Warenkorb hinzugefügt',
      'gold_cart_shared': 'Warenkorb geteilt',
      'gold_cart_title': 'Mein Gold-Kauf',
      'gold_created_with': 'Erstellt mit Currency Gold App',
      'gold_clear_title': 'Warenkorb leeren?',
      'gold_clear_confirm': 'Möchtest du wirklich alle',
      'gold_clear_confirm2': 'Einträge entfernen?',
      'gold_cancel': 'Abbrechen',
      'gold_clear': 'Leeren',
      'gold_removed': 'Eintrag entfernt',
      'gold_all_removed': 'Alle Einträge entfernt',
      'gold_undo': 'Rückgängig',
      'gold_updated': 'Goldpreise aktualisiert',
      'gold_offline': 'Offline-Modus',
      'gold_offline_sub': 'Keine Verbindung zum Server. Es werden gespeicherte Daten angezeigt, die möglicherweise veraltet sind.',
      'gold_no_connection': 'Keine Internetverbindung. Bitte prüfe deine Verbindung.',
      'gold_retry': 'Erneut versuchen',
      // Währungs-Tab
      'currency_search': 'Währung suchen...',
      'currency_base': 'Basiswährung',
      'currency_amount': 'Betrag in',
      'currency_copied': 'Betrag kopiert',
      'currency_fav_added': 'zu Favoriten hinzugefügt',
      'currency_fav_removed': 'aus Favoriten entfernt',
      'currency_fav_add': 'Zu Favoriten hinzufügen',
      'currency_fav_remove': 'Aus Favoriten entfernen',
      'currency_no_rates': 'Keine Währungen verfügbar',
      'currency_updated': 'Aktualisiert',
      // Zakat
      'zakat_button': 'Zakat berechnen',
      'zakat_title': 'Zakat-Berechnung',
      'zakat_subtitle': '(1/40 des Goldwertes = 2,5%)',
      'zakat_per_item': 'Zakat',
      'zakat_total': 'Gesamt Zakat',
      'zakat_basis': 'Grundlage: Händlerpreis',
      'zakat_close': 'Schließen',
      'zakat_empty': 'Keine Artikel im Warenkorb für die Zakat-Berechnung.',
      // Händleraufschlag
      'settings_dealer': 'Händleraufschlag',
      'settings_dealer_sub': 'Aufschlag auf den Spot-Preis',
      'settings_dealer_off': 'Kein Aufschlag (nur Spot)',
    },
    'en': {
      'app_title': 'KaratExchange',
      'tab_currency': 'Currency',
      'tab_gold': 'Gold',
      'tab_settings': 'Settings',
      'tab_debug': 'Debug',
      'settings_title': 'Settings',
      'settings_design': 'Appearance',
      'settings_light': 'Light',
      'settings_dark': 'Dark',
      'settings_system': 'System Default',
      'settings_system_sub': 'Automatically adapts to your device',
      'settings_haptic': 'Haptic Feedback',
      'settings_haptic_all': 'All Actions',
      'settings_haptic_all_sub': 'Vibration on all interactions',
      'settings_haptic_important': 'Important Only',
      'settings_haptic_important_sub': 'Vibration on important actions only',
      'settings_haptic_off': 'Off',
      'settings_haptic_off_sub': 'No vibration',
      'settings_language': 'Language',
      'settings_zakat': 'Zakat Mode',
      'settings_zakat_sub': 'Show Zakat calculation in Gold tab',
      'settings_legal': 'Legal',
      'settings_privacy': 'Privacy Policy',
      'settings_info': 'Your settings are saved locally and not transmitted.',
      'gold_coin': 'Coin',
      'gold_currency': 'Currency',
      'gold_quantity': 'Quantity',
      'gold_add': 'Add',
      'gold_spot': 'Spot',
      'gold_dealer': 'Dealer',
      'gold_total_spot': 'Total Spot',
      'gold_total_dealer': 'Total Dealer',
      'gold_remove_all': 'Remove All',
      'gold_share': 'Share Cart',
      'gold_added_to_cart': 'added to cart',
      'gold_cart_shared': 'Cart shared',
      'gold_cart_title': 'My Gold Purchase',
      'gold_created_with': 'Created with Currency Gold App',
      'gold_clear_title': 'Clear Cart?',
      'gold_clear_confirm': 'Do you really want to remove all',
      'gold_clear_confirm2': 'items?',
      'gold_cancel': 'Cancel',
      'gold_clear': 'Clear',
      'gold_removed': 'Item removed',
      'gold_all_removed': 'All items removed',
      'gold_undo': 'Undo',
      'gold_updated': 'Gold prices updated',
      'gold_offline': 'Offline Mode',
      'gold_offline_sub': 'No server connection. Displaying cached data which may be outdated.',
      'gold_no_connection': 'No internet connection. Please check your connection.',
      'gold_retry': 'Retry',
      'currency_search': 'Search currency...',
      'currency_base': 'Base currency',
      'currency_amount': 'Amount in',
      'currency_copied': 'Amount copied',
      'currency_fav_added': 'added to favorites',
      'currency_fav_removed': 'removed from favorites',
      'currency_fav_add': 'Add to favorites',
      'currency_fav_remove': 'Remove from favorites',
      'currency_no_rates': 'No currencies available',
      'currency_updated': 'Updated',
      'zakat_button': 'Calculate Zakat',
      'zakat_title': 'Zakat Calculation',
      'zakat_subtitle': '(1/40 of gold value = 2.5%)',
      'zakat_per_item': 'Zakat',
      'zakat_total': 'Total Zakat',
      'zakat_basis': 'Based on: Dealer price',
      'zakat_close': 'Close',
      'zakat_empty': 'No items in cart for Zakat calculation.',
      'settings_dealer': 'Dealer Markup',
      'settings_dealer_sub': 'Markup on spot price',
      'settings_dealer_off': 'No markup (spot only)',
    },
    'tr': {
      'app_title': 'KaratExchange',
      'tab_currency': 'Döviz',
      'tab_gold': 'Altın',
      'tab_settings': 'Ayarlar',
      'tab_debug': 'Debug',
      'settings_title': 'Ayarlar',
      'settings_design': 'Görünüm',
      'settings_light': 'Açık',
      'settings_dark': 'Koyu',
      'settings_system': 'Sistem Varsayılanı',
      'settings_system_sub': 'Cihazınıza otomatik uyum sağlar',
      'settings_haptic': 'Titreşim Geri Bildirimi',
      'settings_haptic_all': 'Tüm İşlemler',
      'settings_haptic_all_sub': 'Tüm etkileşimlerde titreşim',
      'settings_haptic_important': 'Yalnızca Önemli',
      'settings_haptic_important_sub': 'Yalnızca önemli işlemlerde titreşim',
      'settings_haptic_off': 'Kapalı',
      'settings_haptic_off_sub': 'Titreşim yok',
      'settings_language': 'Dil',
      'settings_zakat': 'Zekât Modu',
      'settings_zakat_sub': 'Altın sekmesinde zekât hesabını göster',
      'settings_legal': 'Hukuki',
      'settings_privacy': 'Gizlilik Politikası',
      'settings_info': 'Ayarlarınız yalnızca yerel olarak kaydedilir ve iletilmez.',
      'gold_coin': 'Madeni Para',
      'gold_currency': 'Para Birimi',
      'gold_quantity': 'Adet',
      'gold_add': 'Ekle',
      'gold_spot': 'Spot',
      'gold_dealer': 'Bayi',
      'gold_total_spot': 'Toplam Spot',
      'gold_total_dealer': 'Toplam Bayi',
      'gold_remove_all': 'Tümünü Kaldır',
      'gold_share': 'Sepeti Paylaş',
      'gold_added_to_cart': 'sepete eklendi',
      'gold_cart_shared': 'Sepet paylaşıldı',
      'gold_cart_title': 'Altın Alımım',
      'gold_created_with': 'Currency Gold App ile oluşturuldu',
      'gold_clear_title': 'Sepeti Temizle?',
      'gold_clear_confirm': 'Gerçekten tüm',
      'gold_clear_confirm2': 'öğeyi kaldırmak istiyor musunuz?',
      'gold_cancel': 'İptal',
      'gold_clear': 'Temizle',
      'gold_removed': 'Öğe kaldırıldı',
      'gold_all_removed': 'Tüm öğeler kaldırıldı',
      'gold_undo': 'Geri Al',
      'gold_updated': 'Altın fiyatları güncellendi',
      'gold_offline': 'Çevrimdışı Mod',
      'gold_offline_sub': 'Sunucu bağlantısı yok. Güncel olmayan önbelleğe alınmış veriler gösteriliyor.',
      'gold_no_connection': 'İnternet bağlantısı yok. Lütfen bağlantınızı kontrol edin.',
      'gold_retry': 'Yeniden Dene',
      'currency_search': 'Para birimi ara...',
      'currency_base': 'Baz para birimi',
      'currency_amount': 'Tutar:',
      'currency_copied': 'Tutar kopyalandı',
      'currency_fav_added': 'favorilere eklendi',
      'currency_fav_removed': 'favorilerden kaldırıldı',
      'currency_fav_add': 'Favorilere ekle',
      'currency_fav_remove': 'Favorilerden kaldır',
      'currency_no_rates': 'Para birimi bulunamadı',
      'currency_updated': 'Güncellendi',
      'zakat_button': 'Zekât Hesapla',
      'zakat_title': 'Zekât Hesabı',
      'zakat_subtitle': '(Altın değerinin 1/40\'ı = %2,5)',
      'zakat_per_item': 'Zekât',
      'zakat_total': 'Toplam Zekât',
      'zakat_basis': 'Dayanak: Bayi fiyatı',
      'zakat_close': 'Kapat',
      'zakat_empty': 'Zekât hesabı için sepette ürün yok.',
      'settings_dealer': 'Satıcı Fiyat Farkı',
      'settings_dealer_sub': 'Spot fiyatına eklenen fark',
      'settings_dealer_off': 'Fark yok (yalnızca spot)',
    },
    'fr': {
      'app_title': 'KaratExchange',
      'tab_currency': 'Devises',
      'tab_gold': 'Or',
      'tab_settings': 'Paramètres',
      'tab_debug': 'Debug',
      'settings_title': 'Paramètres',
      'settings_design': 'Apparence',
      'settings_light': 'Clair',
      'settings_dark': 'Sombre',
      'settings_system': 'Par défaut du système',
      'settings_system_sub': 'S\'adapte automatiquement à votre appareil',
      'settings_haptic': 'Retour haptique',
      'settings_haptic_all': 'Toutes les actions',
      'settings_haptic_all_sub': 'Vibration sur toutes les interactions',
      'settings_haptic_important': 'Important seulement',
      'settings_haptic_important_sub': 'Vibration uniquement pour les actions importantes',
      'settings_haptic_off': 'Désactivé',
      'settings_haptic_off_sub': 'Pas de vibration',
      'settings_language': 'Langue',
      'settings_zakat': 'Mode Zakat',
      'settings_zakat_sub': 'Afficher le calcul de la zakat dans l\'onglet Or',
      'settings_legal': 'Mentions légales',
      'settings_privacy': 'Politique de confidentialité',
      'settings_info': 'Vos paramètres sont enregistrés localement et ne sont pas transmis.',
      'gold_coin': 'Pièce',
      'gold_currency': 'Devise',
      'gold_quantity': 'Quantité',
      'gold_add': 'Ajouter',
      'gold_spot': 'Spot',
      'gold_dealer': 'Revendeur',
      'gold_total_spot': 'Total Spot',
      'gold_total_dealer': 'Total Revendeur',
      'gold_remove_all': 'Tout supprimer',
      'gold_share': 'Partager le panier',
      'gold_added_to_cart': 'ajouté au panier',
      'gold_cart_shared': 'Panier partagé',
      'gold_cart_title': 'Mon achat d\'or',
      'gold_created_with': 'Créé avec Currency Gold App',
      'gold_clear_title': 'Vider le panier?',
      'gold_clear_confirm': 'Voulez-vous vraiment supprimer les',
      'gold_clear_confirm2': 'articles?',
      'gold_cancel': 'Annuler',
      'gold_clear': 'Vider',
      'gold_removed': 'Article supprimé',
      'gold_all_removed': 'Tous les articles supprimés',
      'gold_undo': 'Annuler',
      'gold_updated': 'Prix de l\'or mis à jour',
      'gold_offline': 'Mode hors ligne',
      'gold_offline_sub': 'Pas de connexion au serveur. Affichage des données en cache qui peuvent être obsolètes.',
      'gold_no_connection': 'Pas de connexion internet. Veuillez vérifier votre connexion.',
      'gold_retry': 'Réessayer',
      'currency_search': 'Rechercher une devise...',
      'currency_base': 'Devise de base',
      'currency_amount': 'Montant en',
      'currency_copied': 'Montant copié',
      'currency_fav_added': 'ajouté aux favoris',
      'currency_fav_removed': 'retiré des favoris',
      'currency_fav_add': 'Ajouter aux favoris',
      'currency_fav_remove': 'Retirer des favoris',
      'currency_no_rates': 'Aucune devise disponible',
      'currency_updated': 'Mis à jour',
      'zakat_button': 'Calculer la Zakat',
      'zakat_title': 'Calcul de la Zakat',
      'zakat_subtitle': '(1/40 de la valeur or = 2,5%)',
      'zakat_per_item': 'Zakat',
      'zakat_total': 'Total Zakat',
      'zakat_basis': 'Base: prix revendeur',
      'zakat_close': 'Fermer',
      'zakat_empty': 'Aucun article dans le panier pour le calcul de la zakat.',
      'settings_dealer': 'Commission revendeur',
      'settings_dealer_sub': 'Supplément au prix spot',
      'settings_dealer_off': 'Pas de commission (spot uniquement)',
    },
    'es': {
      'app_title': 'KaratExchange',
      'tab_currency': 'Divisas',
      'tab_gold': 'Oro',
      'tab_settings': 'Ajustes',
      'tab_debug': 'Debug',
      'settings_title': 'Ajustes',
      'settings_design': 'Apariencia',
      'settings_light': 'Claro',
      'settings_dark': 'Oscuro',
      'settings_system': 'Predeterminado del sistema',
      'settings_system_sub': 'Se adapta automáticamente a tu dispositivo',
      'settings_haptic': 'Retroalimentación háptica',
      'settings_haptic_all': 'Todas las acciones',
      'settings_haptic_all_sub': 'Vibración en todas las interacciones',
      'settings_haptic_important': 'Solo importantes',
      'settings_haptic_important_sub': 'Vibración solo en acciones importantes',
      'settings_haptic_off': 'Desactivado',
      'settings_haptic_off_sub': 'Sin vibración',
      'settings_language': 'Idioma',
      'settings_zakat': 'Modo Zakat',
      'settings_zakat_sub': 'Mostrar el cálculo del zakat en la pestaña Oro',
      'settings_legal': 'Legal',
      'settings_privacy': 'Política de privacidad',
      'settings_info': 'Tu configuración se guarda localmente y no se transmite.',
      'gold_coin': 'Moneda',
      'gold_currency': 'Divisa',
      'gold_quantity': 'Cantidad',
      'gold_add': 'Añadir',
      'gold_spot': 'Spot',
      'gold_dealer': 'Distribuidor',
      'gold_total_spot': 'Total Spot',
      'gold_total_dealer': 'Total Distribuidor',
      'gold_remove_all': 'Eliminar todo',
      'gold_share': 'Compartir carrito',
      'gold_added_to_cart': 'añadido al carrito',
      'gold_cart_shared': 'Carrito compartido',
      'gold_cart_title': 'Mi compra de oro',
      'gold_created_with': 'Creado con Currency Gold App',
      'gold_clear_title': '¿Vaciar carrito?',
      'gold_clear_confirm': '¿Realmente quieres eliminar los',
      'gold_clear_confirm2': 'artículos?',
      'gold_cancel': 'Cancelar',
      'gold_clear': 'Vaciar',
      'gold_removed': 'Artículo eliminado',
      'gold_all_removed': 'Todos los artículos eliminados',
      'gold_undo': 'Deshacer',
      'gold_updated': 'Precios del oro actualizados',
      'gold_offline': 'Modo sin conexión',
      'gold_offline_sub': 'Sin conexión al servidor. Se muestran datos en caché que pueden estar desactualizados.',
      'gold_no_connection': 'Sin conexión a internet. Por favor, comprueba tu conexión.',
      'gold_retry': 'Reintentar',
      'currency_search': 'Buscar divisa...',
      'currency_base': 'Divisa base',
      'currency_amount': 'Importe en',
      'currency_copied': 'Importe copiado',
      'currency_fav_added': 'añadido a favoritos',
      'currency_fav_removed': 'eliminado de favoritos',
      'currency_fav_add': 'Añadir a favoritos',
      'currency_fav_remove': 'Eliminar de favoritos',
      'currency_no_rates': 'No hay divisas disponibles',
      'currency_updated': 'Actualizado',
      'zakat_button': 'Calcular Zakat',
      'zakat_title': 'Cálculo de Zakat',
      'zakat_subtitle': '(1/40 del valor del oro = 2,5%)',
      'zakat_per_item': 'Zakat',
      'zakat_total': 'Total Zakat',
      'zakat_basis': 'Base: precio distribuidor',
      'zakat_close': 'Cerrar',
      'zakat_empty': 'No hay artículos en el carrito para calcular el zakat.',
      'settings_dealer': 'Comisión del distribuidor',
      'settings_dealer_sub': 'Suplemento al precio spot',
      'settings_dealer_off': 'Sin comisión (solo spot)',
    },
  };
}
